import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, BookOpen, Check, ChevronDown, Database, FileCheck2, GitBranch, Layers, ShieldCheck } from 'lucide-react';
import { api, errorMessage } from '../api';
import type { Evidence as EvidenceData, Source } from '../types';
import { day, readable, titleCase, number, percent } from '../format';
import WorkspaceExecution, { ScenarioTable } from './WorkspaceExecution';
import type { RecordedScenario } from './WorkspaceExecution';
import { ErrorNotice, Metric, Note, Spinner, Tag } from './UI';

type BenchmarkSummary = { all_feasible?:boolean;unique_runs?:number;primary_improvement_pct_min?:number;primary_improvement_pct_max?:number;primary_improvement_pct_median?:number };

function sourceEntries(sources:EvidenceData['manifest']['sources']):Source[] {
  if (Array.isArray(sources)) return sources;
  if (sources && typeof sources === 'object') return Object.entries(sources).map(([name,value]) => ({name,...(typeof value === 'object' && value ? value : {url:typeof value === 'string' ? value : undefined})}));
  return [];
}
function safeLink(value:unknown) { if(typeof value !== 'string') return undefined;try {const url = new URL(value);return ['http:','https:'].includes(url.protocol) ? url.href : undefined;}catch{return undefined;} }

export default function Evidence() {
  const [data,setData] = useState<EvidenceData|null>(null);
  const [error,setError] = useState('');
  const [version,setVersion] = useState(0);
  const benchmarkSummary = data?.evaluation?.summary as BenchmarkSummary|undefined;
  const benchmarkScenarios = (data?.evaluation?.scenarios ?? data?.evaluation?.results ?? []) as RecordedScenario[];
  useEffect(() => {
    const controller = new AbortController();setError('');
    api<EvidenceData>('/evidence',{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setData(result);}).catch(e => {if (!controller.signal.aborted)setError(errorMessage(e));});
    return () => controller.abort();
  },[version]);
  return <>
    <div className="page-heading"><div><div className="eyebrow">NO BLACK BOX. NO BORROWED CERTAINTY.</div><h1>A clear line from data to decision.</h1><p>Understand what goes into a proposal, what it can tell you, and what still needs local knowledge.</p></div><Tag tone="green"><BookOpen size={13}/> Open methodology</Tag></div>
    {error && <ErrorNotice message={error} retry={() => setVersion(x => x+1)}/>}
    {!data && !error && <Spinner label="Loading sources and methodology…"/>}
    {data && <>
      <section className="evidence-hero"><div className="evidence-symbol"><ShieldCheck size={31}/></div><div><div className="eyebrow light">TRANSPARENCY IS PART OF THE PRODUCT</div><h2>A signal for review.<br/>A starting point for support.</h2><p>HawkerBridge identifies neighbourhoods to investigate. It does not identify food-insecure individuals, establish walking accessibility, or predict how many residents will request a meal.</p></div><dl><div><dt>Population reference</dt><dd>{String(data.manifest.population_year ?? 'See source')}</dd></div><div><dt>Snapshot fetched</dt><dd>{data.manifest.fetched_at ? day(data.manifest.fetched_at) : 'Not reported'}</dd></div><div><dt>Closure schedule</dt><dd>{String(data.manifest.closures_year ?? 'See source')}</dd></div></dl></section>
      {data.workspace_execution && <WorkspaceExecution publication={data.workspace_execution} evaluation={data.cloud_evaluation}/>}
      <section className="panel"><div className="panel-heading"><div><div className="eyebrow">THE EVIDENCE CHAIN</div><h2>From public records to a practical proposal</h2></div><GitBranch size={20}/></div><div className="pipeline-steps"><div><span className="pipeline-number">01</span><Database size={23}/><h3>Ingest & govern</h3><p>Collect public centre locations, closure schedules, subzone geometry and population counts. Preserve source provenance.</p><span>Bronze → silver tables</span></div><ArrowDown className="pipeline-arrow" size={20}/><div><span className="pipeline-number">02</span><Layers size={23}/><h3>Find access changes</h3><p>Compare nearest hawker-centre distance before and during closures, using one representative point per subzone.</p><span>Area-level access model</span></div><ArrowDown className="pipeline-arrow" size={20}/><div><span className="pipeline-number">03</span><GitBranch size={23}/><h3>Compare allocations</h3><p>Turn assumed meal uptake and explicit costs into a budget-constrained proposal with a simple baseline comparison.</p><span>Transparent optimisation</span></div><ArrowDown className="pipeline-arrow" size={20}/><div><span className="pipeline-number">04</span><FileCheck2 size={23}/><h3>Review locally</h3><p>Save and export a proposal. Verify demand, safe venues and operational capacity with community partners.</p><span>Human review before action</span></div></div></section>
      <section className="panel sources-panel"><div className="panel-heading"><div><div className="eyebrow">SINGAPORE NATIONAL OPEN DATA</div><h2>Every input has a source</h2></div><Tag>{sourceEntries(data.manifest.sources).length} sources</Tag></div><div className="source-list">{sourceEntries(data.manifest.sources).map((source,index) => {
        const url = safeLink(source.url ?? source.source_url ?? source.download_url);
        const name = source.name ?? source.title ?? source.dataset_name ?? `Public dataset ${index+1}`;
        return <div className="source-row" key={index}><div className="source-icon"><Database size={20}/></div><div><h3>{readable(name)}</h3>{source.description !== undefined && <p>{readable(source.description)}</p>}<div className="source-metadata">{source.dataset_id && <code>{source.dataset_id}</code>}{source.publisher !== undefined && <span>{readable(source.publisher)}</span>}{source.fetched_at !== undefined && <span>Fetched {day(String(source.fetched_at))}</span>}{source.rows !== undefined && <span>{readable(source.rows)} records</span>}</div></div>{url && <a className="source-link" href={url} target="_blank" rel="noreferrer">Source <ArrowUpRight size={16}/></a>}</div>;
      })}</div></section>
      <div className="evidence-grid"><section className="panel"><div className="panel-heading"><div><div className="eyebrow">WHAT THIS MODEL DOES</div><h2>Useful, within its limits</h2></div></div><div className="principles-list"><div><Check size={18}/><p>Flags a subzone when its representative point had a centre within the selected radius, then loses that nearby option during a resolved closure.</p></div><div><Check size={18}/><p>Counts all census residents in those flagged subzones. These are people living in areas to review, not people proven to have lost food access.</p></div><div><Check size={18}/><p>Makes meal uptake, costs, capacity and senior priority explicit, so a community team can challenge each assumption.</p></div><div><Check size={18}/><p>Compares the allocation with a largest-demand-first baseline under the same assumptions.</p></div></div></section><section className="panel limitations-panel"><div className="panel-heading"><div><div className="eyebrow">WHAT LOCAL TEAMS NEED TO CHECK</div><h2>What the data cannot promise</h2></div></div><ul className="limitations-list"><li><strong>Actual walking access.</strong> Straight-line distance does not account for roads, sheltered routes, barriers, mobility or household addresses.</li><li><strong>All food alternatives.</strong> The model does not cover every coffee shop, canteen, restaurant, supermarket or home meal arrangement.</li><li><strong>Current individual need.</strong> Census totals are historical; subzone residents are not individual beneficiaries. Meal uptake is assumed.</li><li><strong>Venue and supplier readiness.</strong> Proposed collection points are not verified locations. Prices, capacity and availability need local confirmation.</li><li><strong>A final closure schedule.</strong> Dates may change and source records may not resolve to a centre. Verify before operational use.</li></ul></section></div>
      {data.manifest.quality && <section className="panel"><div className="panel-heading"><div><div className="eyebrow">VISIBLE DATA QUALITY</div><h2>The snapshot’s quality record</h2></div><ShieldCheck size={20}/></div><div className="quality-grid">{Object.entries(data.manifest.quality).map(([key,value]) => <div key={key}><span>{titleCase(key.replaceAll('_',' '))}</span><strong>{readable(value)}</strong></div>)}</div></section>}
      {data.manifest.limitations?.length ? <Note><strong>Source-specific caveats</strong><ul>{data.manifest.limitations.map((item,i) => <li key={i}>{item}</li>)}</ul></Note> : null}
      <details className="method-details"><summary>Technical methodology record <ChevronDown size={18}/></summary><dl className="technical-record">{Object.entries(data.methodology).map(([key,value]) => <div key={key}><dt>{titleCase(key.replaceAll('_',' '))}</dt><dd>{readable(value)}</dd></div>)}</dl></details>
      {data.evaluation && data.evaluation_status !== 'stale' && <section className="panel benchmark-panel"><div className="panel-heading"><div><div className="eyebrow">COMPUTATIONAL ROBUSTNESS · NOT A FIELD TRIAL</div><h2>Test the proposal, not just the story</h2></div><Tag tone="green">Snapshot-linked benchmark</Tag></div><div className="section-padding benchmark-content">{benchmarkSummary?.unique_runs !== undefined && <div className="metrics-grid planner-metrics"><Metric label={data.evaluation_execution==='databricks' ? 'Cloud evaluation scenarios' : 'Local regression runs'} value={number(benchmarkSummary.unique_runs)} note="Fixed scenarios plus access-radius sensitivity"/><Metric label="Budget & capacity checks" value={benchmarkSummary.all_feasible ? 'All pass' : 'Review'} note="Feasibility in the recorded benchmark"/><Metric label="Primary objective uplift" value={`${percent(benchmarkSummary.primary_improvement_pct_min ?? 0)}–${percent(benchmarkSummary.primary_improvement_pct_max ?? 0)}`} note="9 predeclared scenarios · vs largest demand first"/></div>}<p className="benchmark-explanation">{data.evaluation_execution==='databricks' ? 'This evaluation ran in Databricks. ' : 'These regression checks ran locally against the published snapshot. '}The benchmark compares the policy-weighted allocation objective against largest-demand-first under the same assumptions. These are computational scenarios, not measured social impact or validated meal demand.</p><Note>A larger budget alone may not create more meals. At three localities with capacity of 150 meals each, the operational ceiling is 450 meals; increase verified capacity before increasing spend.</Note>{benchmarkScenarios.length > 0 && <details className="method-details"><summary>View predeclared primary scenarios <ChevronDown size={16}/></summary><ScenarioTable scenarios={benchmarkScenarios.slice(0,9)} caption="Primary allocation benchmark scenarios"/></details>}<details className="method-details"><summary>Evaluation protocol & provenance <ChevronDown size={18}/></summary><dl className="technical-record">{Object.entries(data.evaluation).filter(([key]) => !['scenarios','results','summary'].includes(key)).map(([key,value]) => <div key={key}><dt>{titleCase(key.replaceAll('_',' '))}</dt><dd>{readable(value)}</dd></div>)}</dl></details></div></section>}
      {data.evaluation_status && data.evaluation_status !== 'current' && <Note>{data.evaluation_status === 'stale' ? 'The stored benchmark does not match the current model or data snapshot. Rerun the evaluation before quoting benchmark results.' : 'No current evaluation record is available for this deployment. Run the benchmark against this snapshot before quoting an uplift.'}</Note>}
      <div className="data-ribbon"><ShieldCheck size={16}/><span>No household data. No individual risk scores. No automated service dispatch.</span><span>Community teams keep the decision.</span></div>
    </>}
  </>;
}
