import { useMemo, useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, ChevronDown, CircleHelp, MapPin, Store, Users, UserRound, ShieldCheck } from 'lucide-react';
import type { Analysis, Snapshot } from '../types';
import { day, number, percent, titleCase } from '../format';
import AccessMap from './AccessMap';
import { Empty, Metric, Note, Tag } from './UI';

export default function Overview({ analysis, snapshot, onPlan, onDate, onEvidence }: { analysis: Analysis; snapshot: Snapshot; onPlan: () => void; onDate: (value: string) => void; onEvidence: () => void }) {
  const [selectedArea, setSelectedArea] = useState<string|null>(null);
  const [showAllClosures, setShowAllClosures] = useState(false);
  const [showAllAreas, setShowAllAreas] = useState(false);
  const closed = analysis.centres.filter(c => c.status === 'closed' && (!analysis.planning_areas?.length || analysis.planning_areas.includes(c.planning_area)));
  const affected = analysis.area_ranking.filter(a => a.newly_exposed_residents > 0).sort((a,b) => b.newly_exposed_residents - a.newly_exposed_residents);
  const calendar = useMemo(() => {
    const all = analysis.calendar;
    let start = all.findIndex(d => d.date >= analysis.date);
    if (start < 0) start = Math.max(0, all.length - 14);
    start = Math.min(start,Math.max(0,all.length - 14));
    return all.slice(start,start + 14);
  }, [analysis.calendar,analysis.date]);
  const maxClosed = Math.max(1,...calendar.map(d => d.closed_centres));
  const sourceDate = snapshot.manifest.fetched_at ?? analysis.data_as_of;

  return <>
    <div className="page-heading"><div><div className="eyebrow">THE COMMUNITY CONTINUITY DESK</div><h1>Small closures.<br className="mobile-break"/> Real everyday impact.</h1><p>See where hawker closures leave a gap. Put support where it can make a difference.</p></div><button className="button primary" onClick={onPlan}>Build a support plan <ArrowUpRight size={17}/></button></div>
    <div className="context-line"><span className="context-dot"/>Access outlook <strong>{day(analysis.date, { weekday:'long', day:'numeric', month:'long', year:'numeric' })}</strong><span className="context-separator">/</span><span>{number(analysis.radius_m)} m straight-line threshold</span><button className="text-button" onClick={onEvidence}>How we estimate <CircleHelp size={14}/></button></div>
    <div className="metrics-grid"><Metric label="Scheduled closures" value={<>{number(analysis.summary.closed_centres)}<span className="metric-denominator"> / {number(analysis.summary.total_centres)}</span></>} note={<>{number(analysis.summary.food_stalls_closed)} food stalls in closed centres</>} icon={<Store size={19}/>}/><Metric label="Subzones flagged for review" value={number(analysis.summary.affected_zones)} note={<>{number(affected.length)} planning {affected.length === 1 ? 'area' : 'areas'} with an access change</>} tone="signal" icon={<MapPin size={19}/>}/><Metric label="Residents in flagged subzones" value={number(analysis.summary.newly_exposed_residents)} note={`Census ${snapshot.manifest.population_year ?? '2020'} · area totals, not individual need`} icon={<Users size={19}/>}/><Metric label="Of these, residents aged 65+" value={number(analysis.summary.newly_exposed_seniors)} note={`Census ${snapshot.manifest.population_year ?? '2020'} · local validation required`} icon={<UserRound size={19}/>}/></div>
    <div className="overview-workspace"><section className="panel map-panel"><div className="panel-heading"><div><div className="eyebrow">THE ACCESS PICTURE</div><h2>A neighbourhood view</h2></div><Tag>{number(analysis.radius_m)} m threshold</Tag></div><AccessMap snapshot={snapshot} analysis={analysis} selectedArea={selectedArea} onAreaClear={() => setSelectedArea(null)}/><div className="map-footnote"><span><i className="legend-area"/> Flagged points lose a nearby centre; area totals are a screening proxy.</span><button className="text-button" onClick={onEvidence}>View methodology <ArrowUpRight size={13}/></button></div></section>
    <section className="panel closures-panel"><div className="panel-heading"><div><div className="eyebrow">ON THE SELECTED DAY</div><h2>Closed, for now <span className="count-badge">{closed.length}</span></h2></div><CalendarDays size={19}/></div>
      {closed.length ? <><div className="closure-list">{closed.slice(0,showAllClosures ? undefined : 5).map(c => <button key={c.id} className={`closure-row ${selectedArea === c.planning_area ? 'selected' : ''}`} onClick={() => setSelectedArea(c.planning_area)}><div className="closure-icon"><Store size={18}/></div><div className="closure-body"><strong>{titleCase(c.name)}</strong><span>{titleCase(c.planning_area)} · {number(c.food_stalls)} food stalls</span><div className="closure-tags">{c.active_closures.map(closure => <span key={closure.id}>{closure.kind === 'cleaning' ? 'Cleaning' : 'Works'} · {day(closure.start_date, {day:'numeric',month:'short'})}{closure.end_date !== closure.start_date ? `–${day(closure.end_date,{day:'numeric',month:'short'})}` : ''}</span>)}</div></div><ArrowUpRight size={15}/></button>)}</div>{closed.length > 5 && <button className="list-more" onClick={() => setShowAllClosures(!showAllClosures)}>{showAllClosures ? 'Show fewer centres' : `View all ${closed.length} closures`}<ChevronDown className={showAllClosures ? 'rotate' : ''} size={15}/></button>}</> : <Empty icon={<ShieldCheck size={26}/>} title="No closures on this day">Choose another date in the outlook below to explore a scheduled closure.</Empty>}
      <div className="closure-note"><span className="orange-dot"/> Scheduled dates may change. Verify with the centre before acting.</div>
    </section></div>
    {analysis.summary.newly_exposed_residents === 0 && <Note>No additional subzone representative point loses a nearby hawker centre under this scenario. This does not mean every resident already has nearby access, or that a closure causes no disruption.</Note>}
    <section className="panel outlook-panel"><div className="panel-heading"><div><div className="eyebrow">LOOK AHEAD</div><h2>Plan before the shutters come down</h2></div><span className="caption">Select a day to inspect its closures</span></div>{calendar.length > 0 ? <div className="calendar-chart">{calendar.map(d => <button key={d.date} className={`calendar-day ${d.date === analysis.date ? 'active' : ''}`} aria-label={`${day(d.date)}, ${d.closed_centres} closed centres`} aria-pressed={d.date === analysis.date} onClick={() => onDate(d.date)}><span className="calendar-count">{d.closed_centres}</span><div className="calendar-bar-track"><span style={{height:`${Math.max(5,(d.closed_centres/maxClosed)*100)}%`}}/></div><strong>{day(d.date,{day:'numeric'})}</strong><span>{day(d.date,{weekday:'short'})}</span></button>)}</div> : <p className="section-padding muted">No closure calendar is available for this data snapshot.</p>}<div className="calendar-caption"><span><i className="legend-dot closed"/> Number of scheduled closed centres per day</span>{calendar.length > 0 && <span>{day(calendar[0].date,{day:'numeric',month:'short'})} – {day(calendar[calendar.length-1].date,{day:'numeric',month:'short',year:'numeric'})}</span>}</div></section>
    <section className="panel area-panel"><div className="panel-heading"><div><div className="eyebrow">WHERE TO START</div><h2>Areas that may need a bridge</h2></div><button className="text-button" onClick={onPlan}>Turn insight into a plan <ArrowRight size={16}/></button></div>{affected.length > 0 ? <><div className="table-scroll"><table><thead><tr><th scope="col">Planning area</th><th scope="col">Residents in flagged subzones</th><th scope="col">Aged 65+</th><th scope="col">Modelled coverage</th><th scope="col">Centres / 10k</th><th scope="col">Closures</th><th scope="col" aria-label="View on map"/></tr></thead><tbody>{affected.slice(0,showAllAreas ? undefined : 5).map((area,i) => <tr key={area.planning_area} className={selectedArea === area.planning_area ? 'active-row' : ''}><th scope="row"><span className="rank-number">{String(i+1).padStart(2,'0')}</span>{titleCase(area.planning_area)}</th><td className="numeric signal-text">{number(area.newly_exposed_residents)}</td><td className="numeric">{number(area.newly_exposed_seniors)}</td><td><div className="coverage-cell"><span className="mini-track"><span style={{width:`${Math.min(100,area.coverage_pct)}%`}}/></span><span>{percent(area.coverage_pct)}</span></div></td><td>{area.hawker_centres_per_10000?.toFixed(2) ?? "—"}</td><td>{area.closed_centres} / {area.centres}</td><td><button className="icon-button" aria-label={`Locate ${titleCase(area.planning_area)} on map`} onClick={() => { setSelectedArea(area.planning_area); document.querySelector('.map-panel')?.scrollIntoView({behavior:'smooth',block:'center'}); }}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{affected.length > 5 && <button className="list-more" onClick={() => setShowAllAreas(!showAllAreas)}>{showAllAreas ? 'Show top 5 areas' : `View all ${affected.length} areas`}<ChevronDown size={15}/></button>}</> : <div className="quiet-empty"><ShieldCheck size={20}/><p>No newly flagged planning areas for {day(analysis.date)} at {analysis.radius_m} m.</p></div>}</section>
    <div className="data-ribbon"><ShieldCheck size={16}/><span>Public data, transparent assumptions.</span><span>Population {snapshot.manifest.population_year ?? 'year in source'} · Snapshot {day(sourceDate)}</span><button className="text-button" onClick={onEvidence}>Explore the evidence <ArrowUpRight size={14}/></button></div>
  </>;
}
