import { useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, Coins, CookingPot, FolderHeart, MapPin, Play, RotateCcw, SlidersHorizontal, Sparkles, Store, Users } from 'lucide-react';
import type { Dispatch, SetStateAction } from 'react';
import { api, errorMessage, post } from '../api';
import type { Analysis, AnalysisParams, Optimisation, OptimiseParams, Plan, Snapshot } from '../types';
import { day, money, number, percent, titleCase } from '../format';
import AccessMap from './AccessMap';
import { Empty, ErrorNotice, Metric, Modal, Note, Spinner, Tag } from './UI';

type CostParams = Omit<OptimiseParams,keyof AnalysisParams>;
const defaultCosts: CostParams = { budget:1500,site_cost:300,meal_cost:4,meals_per_site:150,max_sites:3,participation_rate:0.05 };
const assumptions: {key:keyof CostParams;label:string;help:string;min:number;max:number;step:number;prefix?:string}[] = [
  { key:'budget',label:'Daily support budget',help:'Total available for meals and collection localities.',min:1,max:50000,step:50,prefix:'S$' },
  { key:'max_sites',label:'Maximum collection localities',help:'Operational limit for your team in one day.',min:0,max:20,step:1 },
  { key:'meal_cost',label:'Cost per meal',help:'Planning assumption, not a supplier quote.',min:1,max:100,step:0.01,prefix:'S$' },
  { key:'site_cost',label:'Setup cost per locality',help:'One-day coordination and setup assumption.',min:1,max:10000,step:0.01,prefix:'S$' },
  { key:'meals_per_site',label:'Meal capacity per locality',help:'Maximum assumed meals served in one day.',min:1,max:5000,step:1 },
];

export default function Planner({ analysis, snapshot, params, setParams, analysisLoading, onSaved }: { analysis:Analysis; snapshot:Snapshot; params:AnalysisParams; setParams:Dispatch<SetStateAction<AnalysisParams>>; analysisLoading:boolean; onSaved:(id:string) => void }) {
  const [costs,setCosts] = useState<CostParams>(defaultCosts);
  const [result,setResult] = useState<Optimisation|null>(null);
  const [resultHash,setResultHash] = useState('');
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [showScenario,setShowScenario] = useState(false);
  const [showAdvanced,setShowAdvanced] = useState(false);
  const [baseline,setBaseline] = useState<Analysis|null>(null);
  const [saving,setSaving] = useState(false);
  const [saveModal,setSaveModal] = useState(false);
  const [title,setTitle] = useState('');
  const [notes,setNotes] = useState('');
  const [saveError,setSaveError] = useState('');
  const request = useMemo<OptimiseParams>(() => ({...params,...costs}),[params,costs]);
  const requestHash = JSON.stringify(request);
  const stale = !!result && resultHash !== requestHash;
  const activeClosures = snapshot.closures.filter(c => c.start_date <= params.date && c.end_date >= params.date && (!params.planning_areas.length || params.planning_areas.includes(snapshot.centres.find(centre => centre.id === c.centre_id)?.planning_area ?? '')));
  const cleaning = activeClosures.filter(c => c.kind === 'cleaning');
  const centresById = useMemo(() => new Map(snapshot.centres.map(c => [c.id,c])),[snapshot.centres]);
  useEffect(() => {
    if (!params.rescheduled_closure_ids.length) { setBaseline(null); return; }
    const controller = new AbortController();
    post<Analysis>('/analyse',{...params,rescheduled_closure_ids:[]},controller.signal).then(setBaseline).catch(() => { if (!controller.signal.aborted) setBaseline(null); });
    return () => controller.abort();
  },[params]);
  async function run() {
    setBusy(true);setError('');
    try { const output = await post<Optimisation>('/optimise',request);setResult(output);setResultHash(requestHash); }
    catch(e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  async function save() {
    if (stale || analysisLoading || busy) { setSaveError('Your inputs changed. Close this dialog and generate the proposal again before saving.'); return; }
    setSaving(true);setSaveError('');
    try { const plan = await api<Plan>('/plans',{method:'POST',body:JSON.stringify({title,parameters:request,notes})});setSaveModal(false);onSaved(plan.id); }
    catch(e) { setSaveError(errorMessage(e)); } finally { setSaving(false); }
  }
  return <>
    <div className="page-heading"><div><div className="eyebrow">FROM ACCESS GAP TO ACTION PLAN</div><h1>A bridge for the day.</h1><p>Compare a practical meal support proposal within a budget your team can work with.</p></div><Tag tone="orange">Decision support · one day</Tag></div>
    <div className="planner-steps"><div className="active"><span>1</span>Set your assumptions</div><i/><div className={result ? 'active' : ''}><span>2</span>Compare a proposal</div><i/><div><span>3</span>Review with local partners</div></div>
    <div className="planner-layout"><div className="planner-controls">
      <section className="panel scenario-panel"><button className="scenario-heading" onClick={() => setShowScenario(!showScenario)} aria-expanded={showScenario}><div className="scenario-icon"><RotateCcw size={18}/></div><div><strong>What if cleaning moved?</strong><span>Compare schedule coordination</span></div><ChevronDown size={17} className={showScenario ? 'rotate' : ''}/></button>{showScenario && <div className="scenario-body"><p className="caption">Assume selected cleaning closures are rescheduled elsewhere. This does not change the published schedule. Check another day for knock-on effects.</p><div className="closure-options" role="group" aria-label="Cleaning dates to compare">{cleaning.length > 0 ? cleaning.map(c => <label className="closure-checkbox" key={c.id}><input type="checkbox" checked={params.rescheduled_closure_ids.includes(c.id)} onChange={e => setParams(p => ({...p,rescheduled_closure_ids:e.target.checked ? [...p.rescheduled_closure_ids,c.id] : p.rescheduled_closure_ids.filter(id => id !== c.id)}))}/><div><strong>{titleCase(centresById.get(c.centre_id)?.name ?? c.centre_id)}</strong><span>Assume open on {day(params.date,{day:'numeric',month:'short'})}</span></div></label>) : <p className="muted">No cleaning closures to compare on this date.</p>}</div>{activeClosures.some(c => c.kind === 'works') && <p className="caption">Works closures remain in place in this comparison.</p>}{baseline && <div className="scenario-comparison"><span>Residents in flagged subzones</span><div><strong>{number(baseline.summary.newly_exposed_residents)}</strong><ArrowRight size={17}/><strong className="green-text">{number(analysis.summary.newly_exposed_residents)}</strong></div><small>Published schedule → your what-if scenario</small></div>}</div>}</section>
      <section className="panel"><div className="panel-heading"><div><div className="eyebrow">THE PLANNING BRIEF</div><h2>What can your team do?</h2></div><Coins size={20}/></div><form className="assumptions-form" onSubmit={e => {e.preventDefault();void run();}}>
        <div className="planner-date-summary"><CalendarIcon/><div><strong>{day(params.date,{weekday:'short',day:'numeric',month:'long',year:'numeric'})}</strong><span>{params.planning_areas[0] ?? "All Singapore"} · {number(analysis.summary.affected_zones)} subzones flagged · {number(params.radius_m)} m</span></div></div>
        <label className="field budget-field">Daily support budget<div className="input-with-prefix"><span>S$</span><input type="number" value={costs.budget} min={0} max={100000} step="0.01" required onChange={e => setCosts(c => ({...c,budget:Number(e.target.value)}))}/><span className="input-suffix">/ day</span></div><small>Total for meals, coordination and setup.</small></label>
        <div className="budget-presets">{[1000,1500,2500,5000].map(value => <button key={value} type="button" className={costs.budget === value ? 'active' : ''} onClick={() => setCosts(c => ({...c,budget:value}))}>{money(value)}</button>)}</div>
        <label className="field participation-field"><span>Assumed meal uptake <strong>{percent(costs.participation_rate*100)}</strong></span><input type="range" min={1} max={20} step={1} value={costs.participation_rate*100} onChange={e => setCosts(c => ({...c,participation_rate:Number(e.target.value)/100}))}/><div className="range-labels"><span>1% · cautious</span><span>20% · higher demand</span></div><small>Share of residents in flagged subzones who might request a meal. A scenario assumption, not a forecast.</small></label>
        <div className="form-two-col">{assumptions.filter(x => ['max_sites','meal_cost'].includes(x.key)).map(a => <label className="field" key={a.key}>{a.label}<div className="input-with-prefix">{a.prefix && <span>{a.prefix}</span>}<input type="number" min={a.min} max={a.max} step={a.step} value={costs[a.key]} required onChange={e => setCosts(c => ({...c,[a.key]:Number(e.target.value)}))}/></div></label>)}</div>
        <button type="button" className="advanced-toggle" onClick={() => setShowAdvanced(!showAdvanced)} aria-expanded={showAdvanced}><SlidersHorizontal size={15}/> Cost, capacity & priority settings<ChevronDown size={15} className={showAdvanced ? 'rotate' : ''}/></button>
        {showAdvanced && <div className="advanced-fields">{assumptions.filter(x => ['site_cost','meals_per_site'].includes(x.key)).map(a => <label className="field" key={a.key}>{a.label}<div className="input-with-prefix">{a.prefix && <span>{a.prefix}</span>}<input type="number" min={a.min} max={a.max} step={a.step} value={costs[a.key]} required onChange={e => setCosts(c => ({...c,[a.key]:Number(e.target.value)}))}/></div><small>{a.help}</small></label>)}<label className="field">Senior priority weight<select value={params.senior_weight} onChange={e => setParams(p => ({...p,senior_weight:Number(e.target.value)}))}><option value={1}>1× · equal weighting</option><option value={1.5}>1.5× · moderate priority</option><option value={2}>2× · higher priority</option><option value={3}>3× · strongest priority</option></select><small>Policy choice that weights assumed meal benefit for residents aged 65+.</small></label></div>}
        <div className="assumption-summary"><span>Current assumptions</span><p>{money(costs.site_cost)} setup / locality · {number(costs.meals_per_site)} meal capacity · {params.senior_weight}× senior weight</p></div>
        <button className="button primary full" type="submit" disabled={busy || analysisLoading}>{busy ? <Spinner small label="Comparing feasible options…"/> : <>Generate support proposal <ArrowRight size={17}/></>}</button>
        <p className="caption form-note">No venues are booked and no services are dispatched.</p>
      </form></section>

    </div><div className="planner-result">
      {error && <ErrorNotice message={error} retry={() => void run()}/>}
      {!result && <div className="proposal-intro panel"><div className="proposal-art" aria-hidden="true"><div className="proposal-art-top"><span><Store size={25}/></span><i/><span><CookingPot size={29}/></span><i/><span><Users size={25}/></span></div><div className="proposal-art-label">THE EVERYDAY CONTINUITY LOOP</div></div><div className="eyebrow">A PLAN, WITH THE TRADE-OFFS VISIBLE</div><h2>Make the most of<br/>every meal.</h2><p>HawkerBridge compares candidate collection localities to allocate a limited budget, with an explicit priority weight for older residents.</p><div className="proposal-promises"><div><Check size={16}/><span>A budget-feasible, one-day meal proposal</span></div><div><Check size={16}/><span>A fair comparison against largest-demand-first</span></div><div><Check size={16}/><span>Visible assumptions and uptake sensitivity</span></div></div><div className="proposal-start"><ArrowDown size={16}/><span>Set your assumptions, then generate a proposal.</span></div></div>}
      {result && <>
        <section className="proposal-banner"><div><div className="eyebrow light">YOUR SUPPORT PROPOSAL</div><h2>{result.summary.sites_selected > 0 ? `${number(result.summary.total_meals)} planned meals. ${number(result.summary.sites_selected)} proposed ${result.summary.sites_selected === 1 ? 'locality' : 'localities'}.` : 'No feasible meal allocation.'}</h2><p>{result.summary.sites_selected > 0 ? 'A starting point for a conversation with your community partners.' : result.analysis.summary.affected_zones === 0 ? 'No additional subzones are flagged under this access scenario.' : 'Review the budget, setup cost, or capacity assumptions.'}</p></div><button className="button cream" disabled={stale || busy || analysisLoading} onClick={() => { setTitle(`Continuity plan · ${day(result.analysis.date)}`);setSaveError('');setSaveModal(true); }}><FolderHeart size={17}/> Save proposal</button></section>
        {stale && <div className="notice warning" role="status"><RotateCcw size={17}/><span>Inputs have changed. Generate the proposal again before saving; the results below are from the previous run.</span></div>}
        <div className="metrics-grid planner-metrics"><Metric label="Proposed daily cost" value={money(result.summary.spent)} note={`${money(result.summary.unspent)} of ${money(result.summary.budget)} remains`} icon={<Coins size={18}/>}/><Metric label="Planned meal capacity" value={number(result.summary.total_meals)} note={`${number(result.summary.estimated_demand)} meals of assumed demand`} icon={<CookingPot size={18}/>}/><Metric label="Weighted benefit vs baseline" value={<>{result.summary.improvement_pct > 0 ? '+' : ''}{percent(result.summary.improvement_pct)}</>} note="Modelled objective · not measured impact" tone="positive" icon={<Sparkles size={18}/>}/></div>
        <section className="panel candidate-panel"><div className="panel-heading"><div><div className="eyebrow">PROPOSED COLLECTION LOCALITIES</div><h2>A place to start coordinating</h2></div><Tag>{result.summary.solver_status.replaceAll('_',' ')}</Tag></div>{result.sites.length ? <><AccessMap snapshot={snapshot} analysis={result.analysis} sites={result.sites}/><div className="site-list">{result.sites.map((site,i) => <div className="site-row" key={site.zone_id}><span className="site-number">{i+1}</span><div><h3>{titleCase(site.name)}</h3><span>{titleCase(site.planning_area)} · {site.covered_zone_ids.length} subzones in catchment</span></div><div className="site-meals"><strong>{number(site.meals)}</strong><span>planned meals</span></div><div className="site-cost"><strong>{money(site.cost)}</strong><span>daily cost</span></div></div>)}</div></> : <Empty icon={<MapPin size={28}/>} title="No collection localities selected">{result.analysis.summary.affected_zones ? 'Try a higher budget or lower setup costs to create a feasible allocation.' : 'Try a different closure day or access threshold to explore where support may be needed.'}</Empty>}<Note>Localities are represented by subzone points, not booked or verified venues. Confirm an accessible location, operator capacity, dietary needs, and demand before acting.</Note></section>
        <section className="panel comparison-panel"><div className="panel-heading"><div><div className="eyebrow">COMPARE THE TRADE-OFF</div><h2>Why this proposal?</h2></div></div><div className="comparison-body"><p>{result.explanation}</p><div className="comparison-table"><div><span>Planning approach</span><span>Planned meals</span><span>Weighted benefit</span><span>Cost</span></div><div><strong>{result.baseline.name}</strong><span>{number(result.baseline.total_meals)}</span><span>{number(result.baseline.weighted_benefit)}</span><span>{money(result.baseline.spent)}</span></div><div className="highlight"><strong>HawkerBridge proposal</strong><span>{number(result.summary.total_meals)}</span><span>{number(result.summary.weighted_benefit)}</span><span>{money(result.summary.spent)}</span></div></div><p className="caption">Weighted benefit is an allocation objective using your senior weight. It is not a count of unique people served, a price saving, or observed social impact.</p></div></section>
        <section className="panel sensitivity-panel"><div className="panel-heading"><div><div className="eyebrow">KEEP THE UNCERTAINTY IN VIEW</div><h2>What if uptake is different?</h2></div><Users size={20}/></div><div className="table-scroll"><table><thead><tr><th scope="col">Assumed uptake</th><th scope="col">Assumed meal demand</th><th scope="col">Planned meals</th><th scope="col">Meals matched</th><th scope="col">Potential surplus</th><th scope="col">Unmet assumed demand</th></tr></thead><tbody>{result.sensitivity.map((row,i) => <tr key={i}><th scope="row">{percent(row.participation_rate*100)}{row.participation_rate === result.assumptions.participation_rate && <Tag tone="green">Selected</Tag>}</th><td>{number(row.estimated_demand)}</td><td>{number(row.planned_meals)}</td><td>{row.matched_meals === undefined ? "N/A" : number(row.matched_meals)}</td><td>{row.potential_surplus_meals === undefined ? "N/A" : number(row.potential_surplus_meals)}</td><td>{number(row.unmet_demand)}</td></tr>)}</tbody></table></div><p className="section-padding caption">The saved allocation is held fixed as uptake changes; unmatched planned meals may become surplus. Meal uptake is assumed. The population base is all residents in subzones flagged by a representative-point access model. Validate demand locally; avoid interpreting this as a food insecurity forecast.</p></section>
        {result.limitations.length > 0 && <details className="method-details"><summary>Assumptions and limitations <ChevronDown size={17}/></summary><ul>{result.limitations.map((text,i) => <li key={i}>{text}</li>)}</ul></details>}
      </>}
    </div></div>
    {saveModal && <Modal title="Save your support proposal" onClose={() => { if (!saving) setSaveModal(false); }}><form onSubmit={e => {e.preventDefault();void save();}}>{saveError && <ErrorNotice message={saveError}/>}<label className="field">Plan title<input value={title} onChange={e => setTitle(e.target.value)} maxLength={140} required autoFocus/></label><label className="field">Coordination notes <span className="optional">optional</span><textarea value={notes} onChange={e => setNotes(e.target.value)} rows={4} maxLength={4000} placeholder="Venue checks, partners to contact, dietary needs, or assumptions to validate…"/></label><Note>This saves a private draft. A reviewed plan is still a proposal; no partners are contacted and no service is scheduled.</Note><div className="modal-actions"><button type="button" className="button secondary" disabled={saving} onClick={() => setSaveModal(false)}>Cancel</button><button className="button primary" disabled={saving || stale}>{saving ? <Spinner small label="Saving proposal…"/> : <>Save draft <ArrowUpRight size={16}/></>}</button></div></form></Modal>}
  </>;
}

function CalendarIcon() { return <div className="date-icon"><Play size={15} fill="currentColor"/></div>; }
