import { test, expect } from '@playwright/test';
import { mkdir, copyFile, writeFile } from 'node:fs/promises';

// Run only through the explicitly enabled remote CI workflow. This is a real,
// silent product walkthrough for Shivam's voiceover, not simulated UI footage.
test('record the community-continuity walkthrough',async({browser})=>{
  test.skip(process.env.HAWKERBRIDGE_RECORD_DEMO !== '1','Enable record_demo in workflow_dispatch to capture narrated-demo source footage.');
  test.setTimeout(220000);
  const context=await browser.newContext({baseURL:'http://127.0.0.1:8000',viewport:{width:1440,height:1080},recordVideo:{dir:'../output/demo-footage/raw',size:{width:1440,height:1080}},reducedMotion:'reduce'});
  context.setDefaultTimeout(12000);
  const authentication=await context.request.post('/api/auth/demo',{data:{}});
  expect(authentication.ok()).toBe(true);
  const session=await authentication.json();
  const page=await context.newPage();
  const recordingStart=Date.now();
  const cues:{seconds:number;scene:string}[]=[];
  const cue=async(seconds:number,scene:string)=>{
    const delay=seconds*1000-(Date.now()-recordingStart);
    if(delay>0)await page.waitForTimeout(delay);
    cues.push({seconds:Number(((Date.now()-recordingStart)/1000).toFixed(1)),scene});
  };
  await page.goto('/');
  await expect(page.locator('.metric-value').first()).toBeVisible();
  await page.getByLabel('Analysis date').fill('2026-09-28');
  await page.waitForLoadState('networkidle');
  await page.evaluate(()=>document.fonts.ready);
  await page.getByLabel('Analysis date').blur();
  await cue(5,'Overview: resolved closures and subzones flagged for review');
  await cue(18,'Map: select a scheduled closure from the accessible centre list');
  await page.locator('.closure-row').first().click();
  await cue(29,'Planning-area ranking and census limitations');
  await page.locator('.area-panel').scrollIntoViewIfNeeded();
  await cue(42,'Compare a cleaning-date change before proposing support');
  await page.getByRole('button',{name:'Continuity planner',exact:true}).click();
  await page.getByRole('button',{name:/What if cleaning moved/}).click();
  await page.getByRole('checkbox',{name:/Bedok Reservoir Road Blk\s*630/i}).check();
  await expect(page.locator('.scenario-comparison')).toContainText('54,030');
  await page.locator('.scenario-comparison').scrollIntoViewIfNeeded();
  await cue(50,'Restore the published schedule before generating support');
  await page.getByRole('button',{name:/Reset scenario/}).click();
  await expect(page.locator('.updating-pill')).toHaveCount(0);
  await page.getByRole('button',{name:/What if cleaning moved/}).click();
  await cue(52,'Generate the S$1,500 support proposal');
  await page.getByRole('button',{name:'Generate support proposal'}).click();
  await expect(page.locator('.proposal-banner')).toContainText('225');
  await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));
  await cue(69,'Explain unverified collection localities and allocation trade-offs');
  await page.locator('.comparison-panel').scrollIntoViewIfNeeded();
  await cue(82,'Increase budget to S$3,000: planned capacity reaches 450 meals');
  await page.getByLabel('Daily support budget').fill('3000');
  await page.getByRole('button',{name:'Generate support proposal'}).click();
  await expect(page.locator('.proposal-banner')).toContainText('450');
  await page.locator('.proposal-banner').scrollIntoViewIfNeeded();
  await cue(96,'Increase budget to S$6,000: capacity remains 450 meals');
  await page.getByLabel('Daily support budget').fill('6000');
  await page.getByRole('button',{name:'Generate support proposal'}).click();
  await expect(page.locator('.proposal-banner')).toContainText('450');
  await page.locator('.proposal-banner').scrollIntoViewIfNeeded();
  await cue(107,'Show uptake uncertainty, matched meals and potential surplus');
  await page.locator('.sensitivity-panel').scrollIntoViewIfNeeded();
  await cue(114,'Save a real private proposal');
  await page.getByRole('button',{name:'Save proposal',exact:true}).click();
  await page.getByLabel('Plan title',{exact:true}).fill('28 September community continuity');
  await page.getByLabel(/Coordination notes/).fill('Verify accessible venues, dietary requirements, operator capacity, and actual demand before arranging a service.');
  const savedResponse=page.waitForResponse(response=>response.url().endsWith('/api/plans')&&response.request().method()==='POST');
  await page.getByRole('button',{name:'Save draft',exact:true}).click();
  const saved=await(await savedResponse).json();
  await expect(page.getByRole('heading',{name:'28 September community continuity',exact:true})).toBeVisible();
  await cue(121,'Review the proposal and export the coordination PDF');
  await page.getByRole('button',{name:'Mark as reviewed',exact:true}).click();
  for(const checkbox of await page.getByRole('dialog').getByRole('checkbox').all())await checkbox.check();
  await page.getByRole('button',{name:'Mark reviewed',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Export PDF',exact:true}).click();
  await(await downloadPromise).saveAs('../output/demo-footage/recorded-demo-plan.pdf');
  await cue(129,'Evidence: source lineage and area-level limits');
  await page.getByRole('button',{name:'Evidence & methods',exact:true}).click();
  await expect(page.getByRole('heading',{name:'A clear line from data to decision.',exact:true})).toBeVisible();
  await cue(139,'Public datasets and provenance');
  await page.locator('.sources-panel').scrollIntoViewIfNeeded();
  await cue(149,'Benchmark evidence with no measured-impact claims');
  await page.locator('.benchmark-panel').scrollIntoViewIfNeeded();
  await cue(163,'Close with the real community access overview');
  await page.getByRole('button',{name:'Overview',exact:true}).click();
  await cue(173,'End of source footage');
  // Remove the synthetic test record without changing the final visible scene.
  await context.request.delete(`/api/plans/${saved.id}`,{headers:{'X-CSRF-Token':session.csrf_token}});
  const video=page.video();
  await context.close();
  await mkdir('../output/demo-footage',{recursive:true});
  await copyFile(await video!.path(),'../output/demo-footage/hawkerbridge-silent-walkthrough.webm');
  await writeFile('../output/demo-footage/timeline.json',JSON.stringify({format:'Silent, real application recording; add Shivam Gupta voiceover.',cues},null,2));
});
